modulo03/crypto_wallet/config/routes.rb
Rails.application.routes.draw do
  resources :mining_types
  get 'welcome/index'#, ro 'welcome/index'
  get '/inicio', to: 'welcome#index'

  resources :coins
  # get '/coins', to: 'coins#index'


  root to: 'welcome#index' 
 
end

modulo03/crypto_wallet/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

modulo03/crypto_wallet/app/models/coin.rb
class Coin < ApplicationRecord
    belongs_to :mining_type
end

modulo03/crypto_wallet/app/models/mining_type.rb
class MiningType < ApplicationRecord
    has_many :coins
end

modulo03/crypto_wallet/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :set_locale

    def set_locale
        if params[:locale]
            cookies[:locale] = params[:locale]  
        end
        # I18n.locale = params[:locale] || I18n.default_locale

        if cookies[:locale]
            if I18n.locale != cookies[:locale]
            I18n.locale = cookies[:locale]
            end    
        end
    end 
end
    

    # def default_url_options(options = {})
    #     { locale: I18n.locale }.merge options
    # end

modulo03/crypto_wallet/app/controllers/coins_controller.rb
class CoinsController < ApplicationController
  layout "adm"
  before_action :set_coin, only: %i[ show edit update destroy ]
  before_action :set_mining_type_options, only: [ :new, :edit, :update, :create ]
  # GET /coins or /coins.json
  def index
    @coins = Coin.all
  end

  # GET /coins/1 or /coins/1.json
  def show
  end

  # GET /coins/new
  def new
    @coin = Coin.new
  end

  # GET /coins/1/edit
  def edit
  end

  # POST /coins or /coins.json
  def create
    @coin = Coin.new(coin_params)

    respond_to do |format|
      if @coin.save
        format.html { redirect_to coin_url(@coin), notice: "Coin was successfully created." }
        format.json { render :show, status: :created, location: @coin }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @coin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /coins/1 or /coins/1.json
  def update
    respond_to do |format|
      if @coin.update(coin_params)
        format.html { redirect_to coin_url(@coin), notice: "Coin was successfully updated." }
        format.json { render :show, status: :ok, location: @coin }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @coin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /coins/1 or /coins/1.json
  def destroy
    @coin.destroy

    respond_to do |format|
      format.html { redirect_to coins_url, notice: "Coin was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  def set_mining_type_options 
    @mining_type_options = MiningType.all.pluck(:description, :id)
  end

    def set_coin
      @coin = Coin.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def coin_params
      params.require(:coin).permit(:description, :acronym, :url_image, :mining_type_id)
    end
end

modulo03/crypto_wallet/app/controllers/mining_types_controller.rb
class MiningTypesController < ApplicationController
  before_action :set_mining_type, only: %i[ show edit update destroy ]

  # GET /mining_types or /mining_types.json
  def index
    @mining_types = MiningType.all
  end

  # GET /mining_types/1 or /mining_types/1.json
  def show
  end

  # GET /mining_types/new
  def new
    @mining_type = MiningType.new
  end

  # GET /mining_types/1/edit
  def edit
  end

  # POST /mining_types or /mining_types.json
  def create
    @mining_type = MiningType.new(mining_type_params)

    respond_to do |format|
      if @mining_type.save
        format.html { redirect_to mining_type_url(@mining_type), notice: "Mining type was successfully created." }
        format.json { render :show, status: :created, location: @mining_type }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @mining_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mining_types/1 or /mining_types/1.json
  def update
    respond_to do |format|
      if @mining_type.update(mining_type_params)
        format.html { redirect_to mining_type_url(@mining_type), notice: "Mining type was successfully updated." }
        format.json { render :show, status: :ok, location: @mining_type }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @mining_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mining_types/1 or /mining_types/1.json
  def destroy
    @mining_type.destroy

    respond_to do |format|
      format.html { redirect_to mining_types_url, notice: "Mining type was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mining_type
      @mining_type = MiningType.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def mining_type_params
      params.require(:mining_type).permit(:description, :acronym)
    end
end

modulo03/crypto_wallet/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @nome = params[:nome]
  end
end

modulo03/crypto_wallet/app/helpers/application_helper.rb
module ApplicationHelper
    def data_br(data_us)
        data_us.strftime("%d/%m/%y")
    end

    def locale
        I18n.locale == :en ? "Estados Unidos" : "Português Brasil"
    end

    def nome_aplicacao
        "CRYPTO WALLET APP"
    end 
    def ambiente_rails 
        if Rails.env.development?
            "Desenvolvimento"
            elsif
                Rails.env.production?
                "Produção"
            else 
                "Teste"

            end
        end

end

modulo03/crypto_wallet/app/helpers/coins_helper.rb
module CoinsHelper
end

modulo03/crypto_wallet/app/helpers/mining_types_helper.rb
module MiningTypesHelper
end

modulo03/crypto_wallet/app/helpers/welcome_helper.rb
module WelcomeHelper
end

modulo03/crypto_wallet/app/views/coins/_form.html.erb
<%= form_with(model: coin) do |form| %>
  <% if coin.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(coin.errors.count, "error") %> prohibited this coin from being saved:</h2>

      <ul>
        <% coin.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label :acronym, style: "display: block" %>
    <%= form.text_field :acronym %>
  </div>

    <div>
      <%= form.label :url_image, style: "display: block" %>
      <%= form.text_field :url_image  %>
    </div>


   <div>
      <%= form.label :mining_type_id, style: "display: block" %>
      <%= form.select("mining_type_id", @mining_type_options, {include_blank: "Selecione..."})  %>
    </div> 

  <div class="action">
    <%= form.submit %>
  </div>
<% end %>

modulo03/crypto_wallet/app/views/coins/edit.html.erb
<h1>Editing coin</h1>

<%= render "form", coin: @coin %>

<br>

<div>
  <%= link_to "Show this coin", @coin %> |
  <%= link_to "Back to coins", coins_path %>
</div>

modulo03/crypto_wallet/app/views/coins/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Coins</h1>

<table class="table table-dark table-hover">
  <thead>
    <tr>
      <th><strong><%= @coins.human_attribute_name(:description) %>:</strong></th>
      <th><strong><%= @coins.human_attribute_name(:acronym) %>:</strong></th>
      <th><strong><%= @coins.human_attribute_name(:url_image) %>:</strong></th>
      <th>Ações</th>
    </tr>
  </thead>
  <tbody>
  <% @coins.each do |coin| %>
    <tr>
      <td> 
          <%= coin.description %>
      </td>
      <td>
        <%= coin.acronym %>
      </td>
      <td>
        <img src="<%= coin.url_image  %>"  width="50px" height="50px" />
      </td>
      <td>
        <%= link_to "mostrar essa moeda", coin %>
        <%= link_to "criar nova moeda", new_coin_path %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

modulo03/crypto_wallet/app/views/coins/new.html.erb
<h1>New coin</h1>

<%= render "form", coin: @coin %>

<br>

<div>
  <%= link_to "Back to coins", coins_path %>
</div>

modulo03/crypto_wallet/app/views/coins/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @coin %>

<div>
  <%= link_to t('links.edit'), edit_coin_path(@coin) %> |
  <%= link_to t('links.show'), coins_path %>

  <%= button_to t('links.delete'), @coin, method: :delete, data: {confirm: "Certeza? "} %>
</div>

modulo03/crypto_wallet/app/views/layouts/adm.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CryptoWallet</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>     
    <%= javascript_importmap_tags %>
     <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  </head>

  <body>
  <h1>ADM</h1>
    <%= yield %>
  </body>
  <script>
    
  </script>
</html>

modulo03/crypto_wallet/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CryptoWallet</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>     
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "scaffolds", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag params[:controller], "data-turbo-track": "reload" %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag params[:controller], 'data-turbolinks-track': 'reload' %>

    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  </body>
</html>

modulo03/crypto_wallet/app/views/welcome/_menu.html.erb
<ul>
    <li>
        <%= link_to "Moedas", coins_path %>
    </li>
    <li>
        <%= link_to "Tipos De Mineração", mining_types_path %>
    </li>
</ul>

modulo03/crypto_wallet/app/views/welcome/index.html.erb
<p><%= link_to "Português", root_path(locale: 'pt-BR') %></p>

<p><%= link_to "English", root_path(locale: 'en') %></p>
<h1>Seja Bem Vindo</h1>
<p>O idioma usado nessa aplicação é: <%= t('actual_locale') %></p>
<p>
<strong>
Data:
</strong>
    <%= l(Date.today) %>
</p>
<p><%= I18n.t('hello') %></p>

<%= render "menu" %>

<p><%= nome_aplicacao %></p>
<p>Você está em ambiente de <strong><%= ambiente_rails %></strong></p>
<p><%= @nome %></p>